### ISSUE TITLE
[bug] MySQL Pod  recreate time again 

### ISSUE THREAD

**Issue by acekingke** [radondb/radondb-mysql-kubernetes#319]
**Describe the problem**

**To Reproduce**
1. use sysbench press the databases
2. force reboot QKE

![image](https://user-images.githubusercontent.com/7586502/143973260-c7f5c16e-1c7c-4d0f-9b2c-585ebf5cb6d6.png)

**Expected behavior**

**Environment:**

- RadonDB MySQL version:

**Comment by acekingke** [comment]
![image](https://user-images.githubusercontent.com/7586502/143973450-505f2f75-ce1a-4c1b-a79d-45ea4d9e7f03.png)

**Comment by acekingke** [comment]
Readiness probe failed: [31mxenon.go:49: unexpected error: get.client.error[dial tcp 10.10.28.53:8801: connect: connection refused][39m 2021/11/30 02:35:46.289093 common.go:35: [PANIC] get.client.error[dial tcp 10.10.28.53:8801: connect: connection refused] panic: [PANIC] get.client.error[dial tcp 10.10.28.53:8801: connect: connection refused] goroutine 1 [running]: xbase/xlog.(*Log).Panic(0xc0000f8170, 0x7f51a6, 0x2, 0xc0000c1d08, 0x1, 0x1) /go/src/github.com/radondb/xenon/src/xbase/xlog/xlog.go:164 +0x157 cli/cmd.ErrorOK(0x86b580, 0xc000194060) /go/src/github.com/radondb/xenon/src/cli/cmd/common.go:35 +0x245 cli/cmd.xenonPingCommandFn(0xc000107680, 0xa907a0, 0x0, 0x0) /go/src/github.com/radondb/xenon/src/cli/cmd/xenon.go:49 +0x94 vendor/github.com/spf13/cobra.(*Command).execute(0xc000107680, 0xa907a0, 0x0, 0x0, 0xc000107680, 0xa907a0) /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:603 +0x24b vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa59480, 0xc000000180, 0xc0000c1f78, 0x407ce5) /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:689 +0x2d0 vendor/github.com/spf13/cobra.(*Command).Execute(...) /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:648 main.main() /go/src/github.com/radondb/xenon/src/cli/cli.go:43 +0x31


Liveness probe failed: mysqladmin: connect to server at '127.0.0.1' failed error: 'Can't connect to MySQL server on '127.0.0.1' (111)' Check that mysqld is running on 127.0.0.1 and that the port is 3306. You can check this by doing 'telnet 127.0.0.1 3306'

**Comment by acekingke** [comment]
fix it #318
