### ISSUE TITLE
Xenon readiness probe failed

### ISSUE THREAD

**Issue by zengzhengrong** [radondb/radondb-mysql-kubernetes#706]
```
kubectl apply -f mysql_v1alpha1_mysqlcluster.yaml
```
**Environment:**
**OS: Window wsl ubuntu with k0s**
```
kubectl  get node
NAME   STATUS   ROLES           AGE   VERSION
k0s    Ready    control-plane   11h   v1.23.9+k0s
```
-->

- RadonDB MySQL version: 2.2.1

Overview
```
kubectl.exe get all -n radondb
NAME                                          READY   STATUS             RESTARTS       AGE
pod/radondb-mysql-operator-59d89ffcfd-4s5zg   2/2     Running            0              50m
pod/sample-mysql-0                            1/3     CrashLoopBackOff   12 (73s ago)   9m40s

NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/mysql-operator-metrics   ClusterIP   10.110.154.8     <none>        8443/TCP            50m
service/radondb-mysql-webhook    ClusterIP   10.97.119.193    <none>        443/TCP             50m
service/sample-mysql             ClusterIP   None             <none>        3306/TCP,8082/TCP   9m40s
service/sample-leader            ClusterIP   10.103.84.28     <none>        3306/TCP,8082/TCP   9m40s
service/sample-follower          ClusterIP   10.103.225.254   <none>        3306/TCP,8082/TCP   9m40s

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/radondb-mysql-operator   1/1     1            1           50m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/radondb-mysql-operator-59d89ffcfd   1         1         1       50m

NAME                            READY   AGE
statefulset.apps/sample-mysql   0/3     9m40s
```

Pod describe  detail 
```
kubectl.exe describe pod/sample-mysql-0 -n radondb
Name:             sample-mysql-0
Namespace:        radondb
Priority:         0
Service Account:  sample
Node:             k0s/172.17.0.2
Start Time:       Fri, 07 Oct 2022 23:22:29 +0800
Labels:           app.kubernetes.io/component=database
                  app.kubernetes.io/instance=sample
                  app.kubernetes.io/managed-by=mysql.radondb.com
                  app.kubernetes.io/name=mysql
                  controller-revision-hash=sample-mysql-598fdd6858
                  healthy=no
                  mysql.radondb.com/cluster=sample
                  role=UNKNOW
                  statefulset.kubernetes.io/pod-name=sample-mysql-0
Annotations:      config_rev: 181254
                  kubernetes.io/psp: 00-k0s-privileged
                  secret_rev: 181255
Status:           Running
IP:               10.244.0.35
IPs:
  IP:           10.244.0.35
Controlled By:  StatefulSet/sample-mysql
Init Containers:
  init-sidecar:
    Container ID:  containerd://1d6188f0fddfe225f6d2b515c1dec9091bb97d5aebb528a5f6875ccae6590230
    Image:         radondb/mysql57-sidecar:v2.2.1
    Image ID:      docker.io/radondb/mysql57-sidecar@sha256:fdecc522cac7311d729ed872d43f3791d179e315eba46ac94b8f6c0db61499f9
    Port:          <none>
    Host Port:     <none>
    Command:
      sidecar
      init
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 07 Oct 2022 23:22:30 +0800
      Finished:     Fri, 07 Oct 2022 23:22:40 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:     10m
      memory:  32Mi
    Environment:
      CONTAINER_TYPE:               init-sidecar
      POD_HOSTNAME:                 sample-mysql-0 (v1:metadata.name)
      NAMESPACE:                    radondb
      SERVICE_NAME:                 sample-mysql
      STATEFULSET_NAME:             sample-mysql
      ADMIT_DEFEAT_HEARBEAT_COUNT:  5
      ELECTION_TIMEOUT:             10000
      MYSQL_VERSION:                5.7.34
      RESTORE_FROM:
      CLUSTER_NAME:                 sample
      MYSQL_ROOT_PASSWORD:          <set to the key 'root-password' in secret 'sample-secret'>           Optional: false
      INTERNAL_ROOT_PASSWORD:       <set to the key 'internal-root-password' in secret 'sample-secret'>  Optional: true
      MYSQL_DATABASE:               <set to the key 'mysql-database' in secret 'sample-secret'>          Optional: true
      MYSQL_USER:                   <set to the key 'mysql-user' in secret 'sample-secret'>              Optional: true
      MYSQL_PASSWORD:               <set to the key 'mysql-password' in secret 'sample-secret'>          Optional: true
      MYSQL_REPL_USER:              <set to the key 'replication-user' in secret 'sample-secret'>        Optional: true
      MYSQL_REPL_PASSWORD:          <set to the key 'replication-password' in secret 'sample-secret'>    Optional: true
      METRICS_USER:                 <set to the key 'metrics-user' in secret 'sample-secret'>            Optional: true
      METRICS_PASSWORD:             <set to the key 'metrics-password' in secret 'sample-secret'>        Optional: true
      OPERATOR_USER:                <set to the key 'operator-user' in secret 'sample-secret'>           Optional: true
      OPERATOR_PASSWORD:            <set to the key 'operator-password' in secret 'sample-secret'>       Optional: true
      BACKUP_USER:                  <set to the key 'backup-user' in secret 'sample-secret'>             Optional: true
      BACKUP_PASSWORD:              <set to the key 'backup-password' in secret 'sample-secret'>         Optional: true
    Mounts:
      /docker-entrypoint-initdb.d from init-mysql (rw)
      /etc/localtime from localtime (rw)
      /etc/mysql from mysql-conf (rw)
      /etc/xenon from xenon-conf (rw)
      /mnt/mysql-cm from mysql-cm (rw)
      /mnt/xenon-cm from xenon-cm (rw)
      /scripts from scripts (rw)
      /var/lib/mysql from data (rw)
      /var/lib/xenon from xenon-meta (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jmkrs (ro)
  init-mysql:
    Container ID:  containerd://3b75cf251b211871fd9d7a10882e35abb7b525dad96093a079f3b5f0bdcd4039
    Image:         percona/percona-server:5.7.34
    Image ID:      docker.io/percona/percona-server@sha256:5778b270657aa56dcc9571501f6778bf7a3bb6e73c0bbb1ae8b00d29558ac32a
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      /docker-entrypoint.sh mysqld;if test -f /docker-entrypoint-initdb.d/plugin.sh; then /docker-entrypoint-initdb.d/plugin.sh; fi
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 07 Oct 2022 23:22:41 +0800
      Finished:     Fri, 07 Oct 2022 23:22:41 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      MYSQL_ALLOW_EMPTY_PASSWORD:  yes
      MYSQL_ROOT_HOST:             localhost
      MYSQL_INIT_ONLY:             1
      MYSQL_ROOT_PASSWORD:         <set to the key 'root-password' in secret 'sample-secret'>  Optional: false
    Mounts:
      /docker-entrypoint-initdb.d from init-mysql (rw)
      /etc/localtime from localtime (rw)
      /etc/mysql from mysql-conf (rw)
      /var/lib/mysql from data (rw)
      /var/log/mysql from logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jmkrs (ro)
Containers:
  mysql:
    Container ID:  containerd://a93a100e1af36086cae867894ed5d03f994ff959f0fface32e82349337d1e49d
    Image:         percona/percona-server:5.7.34
    Image ID:      docker.io/percona/percona-server@sha256:5778b270657aa56dcc9571501f6778bf7a3bb6e73c0bbb1ae8b00d29558ac32a
    Port:          3306/TCP
    Host Port:     0/TCP
    Command:
      sh
      -c
      while  [ -f '/var/lib/mysql/sleep-forever' ] ;do sleep 2 ; done; /docker-entrypoint.sh mysqld
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 07 Oct 2022 23:25:55 +0800
      Finished:     Fri, 07 Oct 2022 23:25:55 +0800
    Ready:          False
    Restart Count:  3
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     256Mi
    Liveness:     exec [sh -c if [ -f '/var/lib/mysql/sleep-forever' ] ;then exit 0 ; fi; pgrep mysqld] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:    exec [sh -c if [ -f '/var/lib/mysql/sleep-forever' ] ;then exit 0 ; fi; test $(mysql --defaults-file=/etc/mysql/client.conf -NB -e "SELECT 1") -eq 1] delay=10s timeout=5s period=10s #success=1 #failure=3
    Startup:      exec [sh -c if test $(mysql -uroot -h127.0.0.1 -NB -e "SELECT 1") -eq 1; then sed -i "/^RESET SLAVE ALL;/d" /etc/mysql/conf.d/init.sql; fi] delay=10s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/localtime from localtime (rw)
      /etc/mysql from mysql-conf (rw)
      /var/lib/mysql from data (rw)
      /var/log/mysql from logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jmkrs (ro)
  xenon:
    Container ID:   containerd://52d591e808215d4f48dcb417b2b2170bd02a6cb483ef5823e2e9db77ab316054
    Image:          radondb/xenon:v2.2.1
    Image ID:       docker.io/radondb/xenon@sha256:9376e1177656c3b0a3e99ca3ed20aef6defd1ae57aef90b4395c977564f3d360
    Port:           8801/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 07 Oct 2022 23:25:02 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  256Mi
    Requests:
      cpu:      50m
      memory:   128Mi
    Liveness:   exec [sh -c pgrep xenon && xenoncli xenon ping] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [sh -c xenoncli xenon ping] delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      NAMESPACE:     radondb (v1:metadata.namespace)
      POD_NAME:      sample-mysql-0 (v1:metadata.name)
      AUTO_REBUILD:  false
    Mounts:
      /etc/localtime from localtime (rw)
      /etc/xenon from xenon-conf (rw)
      /scripts from scripts (rw)
      /var/lib/xenon from xenon-meta (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jmkrs (ro)
  backup:
    Container ID:  containerd://1965020455977e7aaa841ca204f72d5f9ae31540bd13e67b4853ded7e11344e2
    Image:         radondb/mysql57-sidecar:v2.2.1
    Image ID:      docker.io/radondb/mysql57-sidecar@sha256:fdecc522cac7311d729ed872d43f3791d179e315eba46ac94b8f6c0db61499f9
    Port:          8082/TCP
    Host Port:     0/TCP
    Command:
      sidecar
      http
    State:          Running
      Started:      Fri, 07 Oct 2022 23:25:02 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   32Mi
    Liveness:   http-get http://:8082/health delay=15s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8082/health delay=5s timeout=5s period=10s #success=1 #failure=3
    Environment:
      CONTAINER_TYPE:       backup
      NAMESPACE:            radondb
      CLUSTER_NAME:         sample
      SERVICE_NAME:         sample-mysql
      MYSQL_ROOT_PASSWORD:
      BACKUP_USER:          <set to the key 'backup-user' in secret 'sample-secret'>      Optional: true
      BACKUP_PASSWORD:      <set to the key 'backup-password' in secret 'sample-secret'>  Optional: true
    Mounts:
      /etc/localtime from localtime (rw)
      /etc/mysql from mysql-conf (rw)
      /var/lib/mysql from data (rw)
      /var/log/mysql from logs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jmkrs (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-sample-mysql-0
    ReadOnly:   false
  mysql-conf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  logs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  mysql-cm:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sample-mysql
    Optional:  false
  xenon-cm:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sample-xenon
    Optional:  false
  xenon-meta:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  scripts:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  xenon-conf:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  init-mysql:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  localtime:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:
  kube-api-access-jmkrs:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m33s                default-scheduler  Successfully assigned radondb/sample-mysql-0 to k0s
  Normal   Pulled     3m33s                kubelet            Container image "radondb/mysql57-sidecar:v2.2.1" already present on machine
  Normal   Created    3m33s                kubelet            Created container init-sidecar
  Normal   Started    3m33s                kubelet            Started container init-sidecar
  Normal   Pulled     3m22s                kubelet            Container image "percona/percona-server:5.7.34" already present on machine
  Normal   Created    3m22s                kubelet            Created container init-mysql
  Normal   Started    3m22s                kubelet            Started container init-mysql
  Normal   Pulling    3m21s                kubelet            Pulling image "radondb/xenon:v2.2.1"
  Normal   Pulled     61s                  kubelet            Successfully pulled image "radondb/xenon:v2.2.1" in 2m19.9773392s
  Normal   Created    61s                  kubelet            Created container xenon
  Normal   Started    61s                  kubelet            Started container xenon
  Normal   Pulled     61s                  kubelet            Container image "radondb/mysql57-sidecar:v2.2.1" already present on machine
  Normal   Created    61s                  kubelet            Created container backup
  Normal   Started    61s                  kubelet            Started container backup
  Normal   Pulled     60s (x2 over 3m21s)  kubelet            Container image "percona/percona-server:5.7.34" already present on machine
  Normal   Created    60s (x2 over 3m21s)  kubelet            Created container mysql
  Normal   Started    60s (x2 over 3m21s)  kubelet            Started container mysql
  Warning  BackOff    52s (x5 over 59s)    kubelet            Back-off restarting failed container
  Warning  Unhealthy  43s                  kubelet            Readiness probe failed: xenon.go:49: unexpected error: get.client.error[dial tcp 10.244.0.35:8801: connect: connection refused]

 2022/10/07 23:25:20.601186 common.go:35:       [PANIC]   get.client.error[dial tcp 10.244.0.35:8801: connect: connection refused]
panic:                                          [PANIC]   get.client.error[dial tcp 10.244.0.35:8801: connect: connection refused]

goroutine 1 [running]:
xbase/xlog.(*Log).Panic(0xc0002062a0, 0x7f67a6, 0x2, 0xc0000f5d08, 0x1, 0x1)
  /go/src/github.com/radondb/xenon/src/xbase/xlog/xlog.go:164 +0x157
cli/cmd.ErrorOK(0x86d140, 0xc0000460c0)
  /go/src/github.com/radondb/xenon/src/cli/cmd/common.go:35 +0x245
cli/cmd.xenonPingCommandFn(0xc0002586c0, 0xa937c0, 0x0, 0x0)
  /go/src/github.com/radondb/xenon/src/cli/cmd/xenon.go:49 +0x94
vendor/github.com/spf13/cobra.(*Command).execute(0xc0002586c0, 0xa937c0, 0x0, 0x0, 0xc0002586c0, 0xa937c0)
  /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:603 +0x24b
vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xa5c480, 0xc000000180, 0xc0000f5f78, 0x407ce5)
  /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:689 +0x2d0
vendor/github.com/spf13/cobra.(*Command).Execute(...)
  /go/src/github.com/radondb/xenon/src/vendor/github.com/spf13/cobra/command.go:648
main.main()
  /go/src/github.com/radondb/xenon/src/cli/cli.go:43 +0x31
```

**Comment by zhl003** [comment]
seems mysql container does not start properly，
Can you provide the log of the mysql container?

**Comment by zengzhengrong** [comment]
> seems mysql container does not start properly， Can you provide the log of the mysql container?

kubectl.exe logs pod/sample-mysql-0 -n radondb
Defaulted container "mysql" out of: mysql, xenon, backup, init-sidecar (init), init-mysql (init)

ERROR: mysqld failed while attempting to check config
command was: "mysqld --verbose --help"

2022-10-08T21:33:02.371302+08:00 0 [ERROR] The server option 'lower_case_table_names' is configured to use case sensitive table names but the data directory is on a case-insensitive file system which is an unsupported combination. Please consider either using a case sensitive file system for your data directory or switching to a case-insensitive table name mode.
2022-10-08T21:33:02.372123+08:00 0 [ERROR] Aborting


Set  lower_case_table_names to 1 to solve that
```
mysqlConf:
      lower_case_table_names: "1"
```
